plugins:
  - jekyll-paginate
paginate: 8
paginate_path: "/blog/page:num/"
destination: "./docs"
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
collections:
  posts:
    output: true
    permalink: /:categories/:title
  games:
    output: true
    order:
      - hyperspace-frontier.md
  commissions:
    output: false
    sort_by: date_added
  miniatures:
    output: false
    sort_by: order