plugins:
  - jekyll-paginate
paginate: 8
paginate_path: "/news/page:num/"
destination: "./docs"
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
collections:
  games:
    output: true
    order:
      - hyperspace-frontier.md
  commissions:
    output: false
    sort_by: date_added