plugins:
  - jekyll-paginate
paginate: 8
paginate_path: "/stories/page:num/"
destination: "./docs"
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
collections:
  games:
    output: true
    order:
      - hyperspace-frontier.md
  commissions:
    output: false
    sort_by: date_added
  miniatures:
    output: false
    sort_by: order